apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer1-org2-deployment
  labels: {
    component: peer1,
    type: peer,
    org: org2
  }
spec:
  replicas: 1
  selector:
    matchLabels:
      component: peer1
      type: peer
      org: org2
  template:
    metadata:
      labels:
        component: peer1
        type: peer
        org: org2
    spec:
      volumes:
        - name: host-mount
          persistentVolumeClaim:
            claimName: efs-burst-persistent-volume-claim
        - name: host
          hostPath:
            path: /var/run
      containers:
        - name: peer1-org2
          image: hyperledger/fabric-peer:1.4.3
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          command: ["sh"]
          args: ["/scripts/start-peer.sh"]
          env:
            - name: CORE_VM_ENDPOINT
              value: unix:///var/run/docker.sock
            - name: CORE_PEER_ADDRESSAUTODETECT
              value: "true"
            - name: CORE_VM_DOCKER_ATTACHOUT
              value: "true"
            - name: CORE_PEER_ID
              value: peer1-org2-service
            - name: CORE_PEER_LISTENADDRESS
              value: 0.0.0.0:7051
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: peer0-org2-service:7051
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: peer1-org2-service:7051
            - name: CORE_PEER_GOSSIP_ENDPOINT
              value: peer1-org2-service:7051
            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: 0.0.0.0:7052
            - name: CORE_PEER_LOCALMSPID
              value: org2
            - name: CORE_PEER_ENDORSER_ENABLED
              value: "true"
            - name: CORE_PEER_GOSSIP_USELEADERELECTION
              value: "true"
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /etc/hyperledger/fabric/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /etc/hyperledger/fabric/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /etc/hyperledger/fabric/tls/ca.crt
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
              value: peer1-org2-couchdb:5984
            - name: CORE_LEDGER_STATE_STATEDATABASE
              value: CouchDB
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: couchdb
                  key: username
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb
                  key: password
          volumeMounts:
            - mountPath: /var/run
              name: host
            - mountPath: /etc/hyperledger/fabric/msp
              name: host-mount
              subPath: files/scripts/crypto-config/peerOrganizations/org2/peers/org2-peer1.default.svc.cluster.local/msp
            - mountPath: /etc/hyperledger/fabric/tls
              name: host-mount
              subPath: files/scripts/crypto-config/peerOrganizations/org2/peers/org2-peer1.default.svc.cluster.local/tls
            - mountPath: /var/hyperledger/production
              name: host-mount
              subPath: state/org2/peers/peer1
            - mountPath: /scripts
              name: host-mount
              subPath: files/scripts
